// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    DataContainer: typeof import('./components/DataContainer.vue')['default']
    DoughnutChart: typeof import('./components/DoughnutChart.vue')['default']
    ErrorRobot: typeof import('./components/ErrorRobot.vue')['default']
    Header: typeof import('./components/Header.vue')['default']
    LevelChart: typeof import('./components/LevelChart.vue')['default']
    Map: typeof import('./components/Map.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}

export {}
